{
 "title": "OP Stack Compose",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Batcher", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Number of pending blocks, not added to a channel yet.",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "op_batcher_default_pending_blocks_count",
     "legendFormat": "pending_blocks_count {{stage}}"
    }
   ]
  },
  {
   "title": "Total number of blocks added to current channel.",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "op_batcher_default_blocks_added_count",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Total size of transactions in pending blocks as they are fetched from L2",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "op_batcher_default_pending_blocks_bytes_total",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "op_batcher_default_pending_blocks_bytes_current",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Total number of input/output bytes per channel.",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    { "expr": "op_batcher_default_input_bytes", "legendFormat": "input {{stage}}" },
    {
     "expr": "op_batcher_default_output_bytes",
     "legendFormat": "output"
    }
   ]
  },
  {
   "title": "Total number of frames of closed channel.",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "op_batcher_default_channel_num_frames",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Batcher Txs",
   "type": "timeseries",
   "description": "TODO: batcher_tx_total is 2x txs sent b/c of bug. See https://github.com/ethereum-optimism/optimism/pull/11438",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "op_batcher_default_batcher_tx_total",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "op_batcher_default_txmgr_confirm_total",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "op_batcher_default_txmgr_current_nonce",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Batcher Tx Publish/Confirm Times",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "op_batcher_default_txmgr_last_confirm_unix",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "op_batcher_default_txmgr_last_publish_unix",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Tx confirmation latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "op_batcher_default_txmgr_tx_confirmed_latency_ms",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Batcher Pending Txs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "op_batcher_default_txmgr_pending_txs",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Batcher Logs",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "{container=\"ops-bedrock-op-batcher-1\"} |= ``"
    }
   ]
  },
  { "title": "Sequencer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "L2 Unsafe Block",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 52 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "op_node_default_refs_number{type=\"l2_unsafe\", layer=\"l2\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "L2 Safe Block",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 52 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "op_node_default_refs_number{type=\"l2_safe\", layer=\"l2\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "L2 Finalized Block",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 52 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "op_node_default_refs_number{type=\"l2_finalized\", layer=\"l2\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "L1 Reorg Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 52 },
   "targets": [
    {
     "expr": "rate(op_node_default_l1_reorg_depth_count[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "L1 Head",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 56 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "op_node_default_refs_number{type=\"l1_head\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "L1 Safe Block",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 56 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "op_node_default_refs_number{type=\"l1_safe\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "L1 Finalized Block",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 56 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "op_node_default_refs_number{type=\"l1_finalized\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Balances", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 } },
  {
   "title": "Batcher Balance",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 61 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "op_batcher_default_balance", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Batcher Balance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 6, "y": 61 },
   "targets": [
    { "expr": "op_batcher_default_balance", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Proposer Balance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 61 },
   "targets": [
    { "expr": "op_proposer_default_balance", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Proposer Balance",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 65 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "op_proposer_default_balance", "legendFormat": "__auto" }
   ]
  }
 ]
}